<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;
use Modules\Finance\Models\Journal;
use Modules\HR\Models\Employee;
use Modules\Inventory\Models\Brand;
use Modules\Inventory\Models\Category;
use Modules\Inventory\Models\Product;
use Modules\Inventory\Models\Unit;
use Modules\Purchasing\Models\PurchaseOrder;
use Modules\Purchasing\Models\PurchaseOrderItem;
use Modules\Purchasing\Models\Vendor;
use Modules\Sales\Models\Customer;
use Modules\Sales\Models\Invoice;
use Modules\Sales\Models\Payment;
use Modules\Sales\Models\SalesOrder;
use Modules\Sales\Models\SalesOrderItem;

class DummyDataSeeder extends Seeder
{
    public function run(): void
    {
        $user = User::first();

        if (!$user) {
            $user = User::create([
                'name' => 'Dummy Admin',
                'email' => 'dummy.admin@next-erp.com',
                'password' => bcrypt('password'),
                'email_verified_at' => now(),
            ]);
        }

        $category = Category::firstOrCreate(
            ['slug' => 'dummy-electronics'],
            [
                'name' => 'Dummy Electronics',
                'description' => 'Dummy category for testing',
                'is_active' => true,
            ]
        );

        $brand = Brand::firstOrCreate(
            ['slug' => 'dummy-brand'],
            [
                'name' => 'Dummy Brand',
                'description' => 'Dummy brand for testing',
                'is_active' => true,
            ]
        );

        $unit = Unit::firstOrCreate(
            ['short_name' => 'pcs'],
            [
                'name' => 'Pieces',
                'is_active' => true,
            ]
        );

        $product = Product::firstOrCreate(
            ['sku' => 'DUMMY-PRD-001'],
            [
                'name' => 'Dummy Product 1',
                'description' => 'Test product generated by seeder',
                'category_id' => $category->id,
                'brand_id' => $brand->id,
                'unit_id' => $unit->id,
                'cost_price' => 150.00,
                'selling_price' => 250.00,
                'minimum_stock' => 5,
                'maximum_stock' => 200,
                'reorder_level' => 10,
                'is_active' => true,
                'type' => 'product',
            ]
        );

        $customer = Customer::firstOrCreate(
            ['customer_code' => 'CUST-DUMMY-001'],
            [
                'name' => 'Dummy Customer',
                'email' => 'dummy.customer@example.com',
                'phone' => '+62 21 10000001',
                'mobile' => '+62 812 1000 0001',
                'address' => 'Dummy Street 1',
                'city' => 'Jakarta',
                'state' => 'DKI Jakarta',
                'country' => 'Indonesia',
                'postal_code' => '10001',
                'credit_limit' => 10000000,
                'payment_terms' => 30,
                'discount_percentage' => 0,
                'is_active' => true,
                'notes' => 'Generated dummy customer',
            ]
        );

        $vendor = Vendor::firstOrCreate(
            ['code' => 'VEN-DUMMY-001'],
            [
                'name' => 'Dummy Vendor',
                'contact_person' => 'Vendor Contact',
                'email' => 'dummy.vendor@example.com',
                'phone' => '+62 21 20000001',
                'mobile' => '+62 813 2000 0001',
                'payment_terms' => 30,
                'credit_limit' => 15000000,
                'address' => 'Dummy Supplier Street',
                'city' => 'Bandung',
                'state' => 'West Java',
                'country' => 'Indonesia',
                'postal_code' => '40111',
                'notes' => 'Generated dummy vendor',
                'is_active' => true,
            ]
        );

        Employee::firstOrCreate(
            ['employee_id' => 'EMP-DUMMY-001'],
            [
                'first_name' => 'Dummy',
                'last_name' => 'Employee',
                'email' => 'dummy.employee@example.com',
                'phone' => '+62 811 3000 0001',
                'date_of_birth' => '1990-01-01',
                'hire_date' => now()->toDateString(),
                'position' => 'Sales Executive',
                'department' => 'Sales',
                'salary' => 7500000,
                'status' => 'active',
                'address' => 'Dummy Employee Address',
            ]
        );

        $salesOrder = SalesOrder::firstOrCreate(
            ['order_number' => 'SO-DUMMY-0001'],
            [
                'customer_id' => $customer->id,
                'quotation_id' => null,
                'user_id' => $user->id,
                'order_date' => now()->toDateString(),
                'delivery_date' => now()->addDays(5)->toDateString(),
                'subtotal' => 0,
                'tax_percentage' => 11,
                'tax_amount' => 0,
                'discount_percentage' => 0,
                'discount_amount' => 0,
                'shipping_cost' => 25000,
                'total' => 0,
                'status' => 'confirmed',
                'payment_status' => 'unpaid',
                'notes' => 'Generated dummy sales order',
            ]
        );

        SalesOrderItem::firstOrCreate(
            [
                'sales_order_id' => $salesOrder->id,
                'product_id' => $product->id,
            ],
            [
                'description' => 'Dummy sales item',
                'quantity' => 3,
                'unit_price' => 250,
                'discount_percentage' => 0,
                'discount_amount' => 0,
                'tax_percentage' => 11,
                'tax_amount' => 0,
                'total' => 0,
            ]
        );

        $salesOrder->refresh();

        $purchaseOrder = PurchaseOrder::firstOrCreate(
            ['po_number' => 'PO-DUMMY-0001'],
            [
                'vendor_id' => $vendor->id,
                'order_date' => now()->toDateString(),
                'expected_delivery_date' => now()->addDays(7)->toDateString(),
                'status' => 'approved',
                'subtotal' => 0,
                'tax_amount' => 0,
                'discount_amount' => 0,
                'shipping_cost' => 15000,
                'total_amount' => 0,
                'outstanding_amount' => 0,
                'payment_terms' => 30,
                'shipping_address' => 'Main Warehouse',
                'notes' => 'Generated dummy purchase order',
                'user_id' => $user->id,
            ]
        );

        PurchaseOrderItem::firstOrCreate(
            [
                'purchase_order_id' => $purchaseOrder->id,
                'product_id' => $product->id,
            ],
            [
                'description' => 'Dummy purchase item',
                'quantity' => 20,
                'received_quantity' => 0,
                'unit_price' => 150,
                'tax_rate' => 11,
                'discount_rate' => 0,
                'total_price' => 0,
            ]
        );

        $poSubtotal = (float) $purchaseOrder->items()->sum('total_price');
        $purchaseOrder->update([
            'subtotal' => $poSubtotal,
            'total_amount' => $poSubtotal + (float) $purchaseOrder->shipping_cost,
            'outstanding_amount' => $poSubtotal + (float) $purchaseOrder->shipping_cost,
        ]);

        $invoice = Invoice::firstOrCreate(
            ['invoice_number' => 'INV-DUMMY-0001'],
            [
                'customer_id' => $customer->id,
                'sales_order_id' => $salesOrder->id,
                'invoice_date' => now()->toDateString(),
                'due_date' => now()->addDays(30)->toDateString(),
                'subtotal' => $salesOrder->subtotal,
                'tax_amount' => $salesOrder->tax_amount,
                'discount_amount' => $salesOrder->discount_amount,
                'total' => $salesOrder->total,
                'paid_amount' => 0,
                'status' => 'pending',
                'notes' => 'Generated dummy invoice',
            ]
        );

        Payment::firstOrCreate(
            ['payment_number' => 'PAY-DUMMY-0001'],
            [
                'customer_id' => $customer->id,
                'invoice_id' => $invoice->id,
                'user_id' => $user->id,
                'payment_date' => now()->toDateString(),
                'amount' => min((float) $invoice->total, 100000),
                'payment_method' => 'bank_transfer',
                'reference_number' => 'DUMMY-REF-001',
                'notes' => 'Generated dummy payment',
            ]
        );

        Journal::firstOrCreate(
            ['journal_number' => 'JRN-DUMMY-0001'],
            [
                'date' => now()->toDateString(),
                'reference' => 'DUMMY-JRN-REF',
                'description' => 'Generated dummy journal entry header',
                'status' => Journal::STATUS_DRAFT,
                'user_id' => $user->id,
            ]
        );

        $this->command->info('Dummy data seeded successfully.');
    }
}
